server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
#    gateway:
#      mvc:
#        routes:
#          - id: customer-service
#            uri: lb://customer-service
#            predicates:
#              - Path=/customers/**
#          - id: product-service
#            uri: lb://product-service
#            predicates:
#              - Path=/products/**